version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.0-python3.11
  user: "50000:0"
  env_file:
    - config/.env.docker
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    _PIP_ADDITIONAL_REQUIREMENTS: 'pandas pyarrow psycopg2-binary==2.9.9 pydantic==2.7.1 pydantic-settings==2.3.1 python-dotenv==1.0.1 requests==2.32.3 tenacity==8.3.0'
    # --- ADICIONE ESTA LINHA ABAIXO ---
    PYTHONPATH: "/opt/airflow"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./.env:/opt/airflow/.env
    # --- ADICIONE ESTAS 3 LINHAS ABAIXO ---
    - ./pipelines:/opt/airflow/pipelines
    - ./core:/opt/airflow/core
    - ./config:/opt/airflow/config
  depends_on:
    postgres:
      condition: service_healthy

services:
  # 1. Banco de Dados do Airflow (O "Cérebro" do orquestrador)
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    restart: always

  # 2. SEU Banco de Dados (A Vitrine para a Weather API)
  postgres_etl:
    image: postgres:15
    container_name: weather_postgres
    environment:
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=victor
      - POSTGRES_DB=projeto_etl
    ports:
      - "5433:5432" # DBeaver vai conectar na porta 5433!
    volumes:
      - postgres_etl_data:/var/lib/postgresql/data
    restart: always

  # 3. Inicializador (Cria o usuário admin e prepara o banco)
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _PIP_ADDITIONAL_REQUIREMENTS: ''  
    user: "0:0"

  # 4. Interface Gráfica (O site localhost:8080)
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  # 5. O Motor de Execução (Quem vai rodar seu código Python)
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres_airflow_data:
  postgres_etl_data: